### ISSUE TITLE
Which is the similarity function in KNN imputation?

### ISSUE THREAD

**Issue by aldoconcha** [eltonlaw/impyute#46]
Hi!

I know that there are many different function to calculate similarity between incomplete vectors, but which one is implemented in the package? I have not found any specification or cite about KNN in the documentation.

**Comment by MinjieSh** [comment]
I believe it is the euclidean distance.

**Comment by eltonlaw** [comment]
Yes, similarity isn't calculated between incomplete vectors, opting for complete vectors. From there impyute uses [SciPy's off the shelf KDTree implementation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.html) which is a direct implementation of [this](https://arxiv.org/pdf/cs/9901013.pdf) IIRC.
