### ISSUE TITLE
Always throws exception

### ISSUE THREAD

**Issue by a-ozbek** [eltonlaw/impyute#8]
https://github.com/eltonlaw/impyute/blob/99fdb5f5117db8ddc9a9d7a2dfccdde685036621/impyute/imputations/ts/arima.py#L31

It will always throw Exception

This line should be changed to:
`isinstance(data, np.ndarray)`

**Comment by eltonlaw** [comment]
Ah, thanks for letting me know! I'll get to it tonight (or you can submit a PR, if you'd like).
